municipios_estados = {
    # Rio de Janeiro (RJ)
    "Volta Redonda": "RJ",
    "São João de Meriti": "RJ",
    "Itaperuna": "RJ",
    "Rio de Janeiro": "RJ",
    "São Gonçalo": "RJ",
    "Petrópolis": "RJ",
    "Rio das Ostras": "RJ",
    "Barra Mansa": "RJ",
    "Maricá": "RJ",
    "Carapebus": "RJ",
    "Itaguaí": "RJ",
    "Porciúncula": "RJ",
    "Armação dos Búzios": "RJ",
    "Casimiro de Abreu": "RJ",
    "Macaé": "RJ",
    "Pinheiral": "RJ",
    "Resende": "RJ",
    "Conceição de Macabu": "RJ",
    "Nova Friburgo": "RJ",
    "Campos dos Goytacazes": "RJ",
    "Iguaba Grande": "RJ",
    "Cabo Frio": "RJ",
    "Angra dos Reis": "RJ",
    "Mangaratiba": "RJ",
    "Teresópolis": "RJ",
    "Belford Roxo": "RJ",
    "Sapucaia": "RJ",
    "São João da Barra": "RJ",
    "Itaocara": "RJ",
    "Sumidouro": "RJ",
    "Rio Bonito": "RJ",
    "Magé": "RJ",
    "Porto Real": "RJ",
    "Carmo": "RJ",
    "Barra do Piraí": "RJ",
    "Engenheiro Paulo de Frontin": "RJ",
    "Araruama": "RJ",
    "Paracambi": "RJ",
    "Vassouras": "RJ",
    "Mendes": "RJ",
    "Paraty": "RJ",
    "Tanguá": "RJ",
    "Cantagalo": "RJ",
    "Santo Antônio de Pádua": "RJ",
    "Itaboraí": "RJ",
    "Valença": "RJ",
    "Queimados": "RJ",
    "Aperibé": "RJ",
    "Quissamã": "RJ",
    "Piraí": "RJ",
    "Guapimirim": "RJ",
    "São Francisco de Itabapoana": "RJ",
    "Nova Iguaçu": "RJ",
    "Niterói": "RJ",
    "São Sebastião do Alto": "RJ",
    "Nilópolis": "RJ",
    "Silva Jardim": "RJ",
    "Areal": "RJ",
    "Macuco": "RJ",
    "Mesquita": "RJ",
    "Duque de Caxias": "RJ",
    "Cordeiro": "RJ",
    "Bom Jesus do Itabapoana": "RJ",
    "Miguel Pereira": "RJ",
    "São Pedro da Aldeia": "RJ",
    "Cardoso Moreira": "RJ",
    "Paty do Alferes": "RJ",
    "Varre-Sai": "RJ",
    "Itatiaia": "RJ",
    "Cambuci": "RJ",
    "Laje do Muriaé": "RJ",
    "Saquarema": "RJ",
    "Quatis": "RJ",
    "Rio das Flores": "RJ",
    "Cachoeiras de Macacu": "RJ",
    "Paraíba do Sul": "RJ",
    "Santa Maria Madalena": "RJ",
    "Arraial do Cabo": "RJ",
    "Trajano de Moraes": "RJ",
    "São José de Ubá": "RJ",
    "Seropédica": "RJ",
    "São Fidélis": "RJ",
    "Italva": "RJ",
    "Três Rios": "RJ",
    "Miracema": "RJ",
    "Japeri": "RJ",
    "Duas Barras": "RJ",
    # São Paulo (SP)
    "São Paulo": "SP",
    "Itapema": "SP",
    "Assis": "SP",
    "Guaratinguetá": "SP",
    "Sorocaba": "SP",
    "Carapicuíba": "SP",
    "Guarulhos": "SP",
    "São José do Rio Preto": "SP",
    "Guarujá": "SP",
    "Santo André": "SP",
    "Taboão da Serra": "SP",
    "Mauá": "SP",
    "Louveira": "SP",
    "Osasco": "SP",
    "Barueri": "SP",
    "Santa Fé do Sul": "SP",
    "Paulínia": "SP",
    "Campo Limpo Paulista": "SP",
    "Campinas": "SP",
    "Atibaia": "SP",
    "Araras": "SP",
    "São José dos Campos": "SP",
    "Piracicaba": "SP",
    "São Vicente": "SP",
    "Pedreira": "SP",
    "Peruíbe": "SP",
    "Rio Claro": "SP",
    "Mogi das Cruzes": "SP",
    "Várzea Paulista": "SP",
    "Porto Feliz": "SP",
    "São Bernardo do Campo": "SP",
    "Queluz": "SP",
    "Pindamonhangaba": "SP",
    "Pederneiras": "SP",
    "Santos": "SP",
    "Itatiba": "SP",
    "Jundiaí": "SP",
    "Americana": "SP",
    "Boracéia": "SP",
    "Votorantim": "SP",
    "Cotia": "SP",
    "Suzano": "SP",
    "Ilha Solteira": "SP",
    "Santana de Parnaíba": "SP",
    "Sumaré": "SP",
    "Caraguatatuba": "SP",
    "Ribeirão Preto": "SP",
    "Hortolândia": "SP",
    "Itu": "SP",
    "Mongaguá": "SP",
    "Santa Bárbara d'Oeste": "SP",
    "Itapecerica da Serra": "SP",
    "Ribeirão Pires": "SP",
    "Mairiporã": "SP",
    "Jacareí": "SP",
    "Santo Antônio de Posse": "SP",
    "São Sebastião": "SP",
    "Duartina": "SP",
    "Valinhos": "SP",
    "Cubatão": "SP",
    "Araçatuba": "SP",
    "Jaboticabal": "SP",
    "Taubaté": "SP",
    "Poá": "SP",
    "São Caetano do Sul": "SP",
    "Marília": "SP",
    "Jaú": "SP",
    "Franco da Rocha": "SP",
    "Catanduva": "SP",
    "Francisco Morato": "SP",
    "Buritama": "SP",
    "Caçapava": "SP",
    "Pereiras": "SP",
    "Cosmópolis": "SP",
    # Minas Gerais (MG)
    "Cajuri": "MG",
    "Belo Oriente": "MG",
    "Carangola": "MG",
    "Santa Luzia": "MG",
    "Simão Pereira": "MG",
    "Santos Dumont": "MG",
    "Chiador": "MG",
    "Volta Grande": "MG",
    "Carmo da Cachoeira": "MG",
    "Mar de Espanha": "MG",
    "Miraí": "MG",
    "Governador Valadares": "MG",
    "Conselheiro Lafaiete": "MG",
    "Contagem": "MG",
    "Pouso Alto": "MG",
    "Juiz de Fora": "MG",
    "Tombos": "MG",
    "Itajubá": "MG",
    "Nova Lima": "MG",
    "Desterro do Melo": "MG",
    "Cruzília": "MG",
    "Iapu": "MG",
    "Lavras": "MG",
    "Além Paraíba": "MG",
    "Muriaé": "MG",
    "Caparaó": "MG",
    "Poços de Caldas": "MG",
    "Campestre": "MG",
    "Sete Lagoas": "MG",
    "Ipatinga": "MG",
    "Montes Claros": "MG",
    "Caxambu": "MG",
    "Coronel Fabriciano": "MG",
    "Teófilo Otoni": "MG",
    "Minas Novas": "MG",
    "Ubá": "MG",
    "Varginha": "MG",
    "Piraúba": "MG",
    "Descoberto": "MG",
    "Lambari": "MG",
    "Nepomuceno": "MG",
    "Mantena": "MG",
    "Itamarati de Minas": "MG",
    "Carmópolis de Minas": "MG",
    "Medina": "MG",
    "Belmiro Braga": "MG",
    "Ibiá": "MG",
    "Caratinga": "MG",
    "Cataguases": "MG",
    "Viçosa": "MG",
    "João Monlevade": "MG",
    "São Bento Abade": "MG",
    "Belo Horizonte": "MG",
    "Patrocínio do Muriaé": "MG",
    "Araguari": "MG",
    "Itamonte": "MG",
    "Uberlândia": "MG",
    "Três Corações": "MG",
    "Perdões": "MG",
    "Betim": "MG",
    "Matias Barbosa": "MG",
    "João Pinheiro": "MG",
    "Aimorés": "MG",
    "Três Pontas": "MG",
    "Iturama": "MG",
    "Santa Rita de Jacutinga": "MG",
    "Formiga": "MG",
    "São João Nepomuceno": "MG",
    # Bahia (BA)
    "Paulo Afonso": "BA",
    "Prado": "BA",
    "Pindobaçu": "BA",
    "Alcobaça": "BA",
    "Catu": "BA",
    "Itamaraju": "BA",
    "Ilhéus": "BA",
    "Ubaitaba": "BA",
    "Conceição do Coité": "BA",
    "São Félix": "BA",
    "Salvador": "BA",
    "Araci": "BA",
    "Coaraci": "BA",
    "Alagoinhas": "BA",
    "Ubatã": "BA",
    "Simões Filho": "BA",
    "Camaçari": "BA",
    "Mata de São João": "BA",
    "Pojuca": "BA",
    "Eunápolis": "BA",
    "Mucuri": "BA",
    "Itambé": "BA",
    "São Francisco do Conde": "BA",
    "Lauro de Freitas": "BA",
    "Itaju do Colônia": "BA",
    "Teixeira de Freitas": "BA",
    "Candeias": "BA",
    "Morro do Chapéu": "BA",
    "São Felipe": "BA",
    "Apuarema": "BA",
    "Boquim": "BA",
    "Juazeiro": "BA",
    "Porto Seguro": "BA",
    "Ipiaú": "BA",
    "Floresta Azul": "BA",
    "Seabra": "BA",
    "Jaguaripe": "BA",
    "Almadina": "BA",
    "Jitaúna": "BA",
    "Brumado": "BA",
    # Ceará (CE)
    "Crateús": "CE",
    "Esperantina": "CE",
    "Independência": "CE",
    "Fortaleza": "CE",
    "Catunda": "CE",
    "Domingos Mourão": "CE",
    "Pacatuba": "CE",
    "Mulungu": "CE",
    "Cariré": "CE",
    "Campos Sales": "CE",
    "Icapuí": "CE",
    "Santa Quitéria": "CE",
    "Sobral": "CE",
    "Trairi": "CE",
    "Guaraciaba do Norte": "CE",
    "Carnaubal": "CE",
    "Aratuba": "CE",
    "Groaíras": "CE",
    "Tabuleiro do Norte": "CE",
    "Camocim": "CE",
    "Reriutaba": "CE",
    "Ipu": "CE",
    # Goiás (GO)
    "Cidade Ocidental": "GO",
    "Goiânia": "GO",
    "Jataí": "GO",
    "Quirinópolis": "GO",
    "Brasília": "GO",
    "Novo Gama": "GO",
    "Santa Helena de Goiás": "GO",
    "Planaltina": "GO",
    "Vicentinópolis": "GO",
    "Anápolis": "GO",
    "Abadia de Goiás": "GO",
    "Bom Jesus de Goiás": "GO",
    "Goianira": "GO",
    "Itumbiara": "GO",
    "Rio Verde": "GO",
    "Goianésia": "GO",
    "Águas Lindas de Goiás": "GO",
    "Valparaíso de Goiás": "GO",
    "Santo Antônio do Descoberto": "GO",
    "Pires do Rio": "GO",
    "Itaberaí": "GO",
    "Mara Rosa": "GO",
    "Caldas Novas": "GO",
    "Luziânia": "GO",
    "Minaçu": "GO",
    # Pernambuco (PE)
    "Nazaré da Mata": "PE",
    "Recife": "PE",
    "Paulista": "PE",
    "Cabo de Santo Agostinho": "PE",
    "Moreno": "PE",
    "Olinda": "PE",
    "Aliança": "PE",
    "Arcoverde": "PE",
    "Ferreiros": "PE",
    "Ibimirim": "PE",
    "Petrolina": "PE",
    "Serra Talhada": "PE",
    "Caruaru": "PE",
    "Limoeiro": "PE",
    "Carpina": "PE",
    "Timbaúba": "PE",
    "São José do Belmonte": "PE",
    "Condado": "PE",
    "Vitória de Santo Antão": "PE",
    "Jaboatão dos Guararapes": "PE",
    "São Lourenço da Mata": "PE",
    "Joaquim Nabuco": "PE",
    "Belo Jardim": "PE",
    "São Vicente Ferrer": "PE",
    "Goiana": "PE",
    "Igarassu": "PE",
    "Macaparana": "PE",
    "Camaragibe": "PE",
    "Abreu e Lima": "PE",
    # Rio Grande do Sul (RS)
    "Porto Alegre": "RS",
    "Rio Grande": "RS",
    "Novo Hamburgo": "RS",
    "Caxias do Sul": "RS",
    "Canoas": "RS",
    "São José do Norte": "RS",
    "Gramado": "RS",
    "Camaquã": "RS",
    "Passo Fundo": "RS",
    "Pelotas": "RS",
    "Cruz Alta": "RS",
    "São Leopoldo": "RS",
    "Arroio do Sal": "RS",
    "Canela": "RS",
    "Encantado": "RS",
    "Gravataí": "RS",
    # Paraíba (PB)
    "Cabedelo": "PB",
    "Pocinhos": "PB",
    "João Pessoa": "PB",
    "Juazeirinho": "PB",
    "Flores": "PB",
    "Campina Grande": "PB",
    "Caraúbas": "PB",
    "Alhandra": "PB",
    "Mari": "PB",
    "Guarabira": "PB",
    "Remígio": "PB",
    "Araçagi": "PB",
    "Cacimba de Dentro": "PB",
    "Fagundes": "PB",
    "Pedro Régis": "PB",
    "Esperança": "PB",
    "Serra Branca": "PB",
    "Rio Tinto": "PB",
    "Sapé": "PB",
    "Caiana": "PB",
    # Amazonas (AM)
    "Manaus": "AM",
    "Carauari": "AM",
    "Tabatinga": "AM",
    "Benjamin Constant": "AM",
    "Tefé": "AM",
    # Pará (PA)
    "Barra dos Coqueiros": "PA",
    "Tucuruí": "PA",
    "Santarém": "PA",
    "Belém": "PA",
    "Paragominas": "PA",
    "Tailândia": "PA",
    "Parauapebas": "PA",
    "Uruará": "PA",
    "Altamira": "PA",
    # Maranhão (MA)
    "Parnaíba": "MA",
    "Natividade": "MA",
    "São Luís": "MA",
    "Vitória do Mearim": "MA",
    # Sergipe (SE)
    "Aracaju": "SE",
    "Nossa Senhora do Socorro": "SE",
    "Rosário do Catete": "SE",
    "Lagarto": "SE",
    "Cantanhede": "SE",
    "Carmópolis": "SE",
    "Nossa Senhora das Dores": "SE",
    "Japaratuba": "SE",
    "Santo Amaro das Brotas": "SE",
    # Santa Catarina (SC)
    "Blumenau": "SC",
    "Ilhota": "SC",
    "Imbituba": "SC",
    "Araquari": "SC",
    "Laguna": "SC",
    "Joinville": "SC",
    "Florianópolis": "SC",
    "Chapecó": "SC",
    "Penha": "SC",
    "Governador Celso Ramos": "SC",
    # Piauí (PI)
    "Teresina": "PI",
    "Buriti dos Montes": "PI",
    "Lagoinha do Piauí": "PI",
    "São Julião": "PI",
    "Pescador": "PI",
    # Alagoas (AL)
    "Delmiro Gouveia": "AL",
    "Maceió": "AL",
    "Poço das Trincheiras": "AL",
    "Conceição de Ipanema": "AL",
    "São Miguel dos Campos": "AL",
    # Mato Grosso do Sul (MS)
    "Corumbá": "MS",
    "Dourados": "MS",
    "Campo Grande": "MS",
    "Ladário": "MS",
    "Terenos": "MS",
    "Ponta Porã": "MS",
    "Batayporã": "MS",
    "Três Lagoas": "MS",
    "Nova Alvorada do Sul": "MS",
    # Tocantins (TO)
    "Tocantins": "TO",
    "Tocantinópolis": "TO",
    "Palma": "TO",
    "Colinas": "TO",
    "Santa Terezinha do Tocantins": "TO",
    "Araguaína": "TO",
    # Rio Grande do Norte (RN)
    "Natal": "RN",
    "João Câmara": "RN",
    # Espírito Santo (ES)
    "Cariacica": "ES",
    "São Mateus": "ES",
    # Paraná (PR)
    "Curitiba": "PR",
    "Jaguariaíva": "PR",
    "Cerro Azul": "PR",
    "Quedas do Iguaçu": "PR",
    "Faxinal": "PR",
    "Tomazina": "PR",
    "Icaraíma": "PR",
    "Fazenda Rio Grande": "PR",
    # Rondônia (RO)
    "Rio Branco": "RO",
    "Porto Velho": "RO",
    "Cacoal": "RO",
    "São Francisco do Guaporé": "RO",
    # Amapá (AP)
    "Macapá": "AP",
    "Amapá": "AP",
    "Santana": "AP",
    # Acre (AC)
    "Cruzeiro do Sul": "AC",
}

mapeamento_regiao = {
    "SP": "Sudeste",
    "RJ": "Sudeste",
    "MG": "Sudeste",
    "ES": "Sudeste",
    "PR": "Sul",
    "SC": "Sul",
    "RS": "Sul",
    "BA": "Nordeste",
    "CE": "Nordeste",
    "PE": "Nordeste",
    "MA": "Nordeste",
    "RN": "Nordeste",
    "PB": "Nordeste",
    "SE": "Nordeste",
    "AL": "Nordeste",
    "PI": "Nordeste",
    "AM": "Norte",
    "PA": "Norte",
    "RO": "Norte",
    "AC": "Norte",
    "RR": "Norte",
    "AP": "Norte",
    "TO": "Norte",
    "GO": "Centro-Oeste",
    "MT": "Centro-Oeste",
    "MS": "Centro-Oeste",
    "DF": "Centro-Oeste",
}
